$:
  tag_push:
    - docker:
        image: node:20
      stages:
        - name: changelog	
          image: cnbcool/changelog	
          exports:
            latestChangeLog: LATEST_CHANGE_LOG	
        - name: create release	
          type: git:release	
          options:	
            title: release	
            description: ${LATEST_CHANGE_LOG}
        - name: npm install
          script: npm install
        - name: install vsce
          script: npm install -g @vscode/vsce
        - name: build
          script: vsce package
        - name: release 上传附件
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - cnb-dev-extension-0.0.6.vsix